### ISSUE TITLE
Range is missing for non enum individuals

### ISSUE THREAD

**Issue by goneall** [spdx/spec-parser#162]
In a recent change to the spec parser, we lost the range for individuals which are not enums.

For example, previously the shape for NoneLicense was:

```
ns3:NoneLicense a owl:NamedIndividual,
        ns3:IndividualLicensingInfo ;
    rdfs:comment """An Individual Value for License where the SPDX data creator determines that no
license is present."""@en ;
    rdfs:range ns3:IndividualLicensingInfo ;
    owl:sameAs <https://spdx.org/rdf/3.0.1/terms/Licensing/None> .
```

The current version of the spec parser generates:

```
ns6:NoneLicense a owl:NamedIndividual,
        ns6:IndividualLicensingInfo ;
    rdfs:comment """An Individual Value for License where the SPDX data creator determines that no
license is present."""@en ;
    owl:sameAs <https://spdx.org/rdf/3.0.1/terms/Licensing/None> .
```

**Comment by goneall** [comment]
OK - Looks like this was intentional: https://github.com/spdx/spec-parser/issues/141

closing issue.

For the Java code generator, I need to figure out a way to determine the class type of an Individual - especially to distinguish it from an enum type.

I'll open a separate issue if I can't figure out a way to do it with the information available.

**Comment by goneall** [comment]
> If it's an `owl:NamedIndividual`:
> 
> * if it has a `range`, it's an enum value;
> * else it's an Individual
> 
> The "class type" you're asking about is the other `a` value. In the example you show `ns6:IndividualLicensingInfo`.

Thanks @zvr for the tips - the `a` value solves the problem.

the enum individuals don't have a `range`.  For example:

```
<https://spdx.org/rdf/3.0.1/terms/AI/EnergyUnitType/kilowattHour> a owl:NamedIndividual,
        ns5:EnergyUnitType ;
    rdfs:label "kilowattHour" ;
    rdfs:comment "Kilowatt-hour."@en .
```

The do have a label, but I'm not sure I can count on that.

The property that references the enum has a range which includes the specific enum values.  I suppose I could search for those, but it's a bit more complex than just looking at the shape of the individual itself.

Let me know if you think using the label would be reliable.

**Comment by zvr** [comment]
This happens when I write something quick after getting a notification on my phone...
Sorry, Garry, you are correct.

Any individual does not have a range; ranges are only valid for properties in RDF.
Therefore, the individuals members of a Vocabulary (enums) also do not have a range.

The _correct_ way would be to find out the type of the individual (the `a` property), and then check this property for further info (the complex way you mention).

Please don't rely on `label` -- at some point everything in our ontology might have such a predicate, based on the Summary section in its definition, for example.
