### ISSUE TITLE
pyshacl doesn't like generated SPDX context

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spec-parser#73]
When using pyshacl to validate the example documents, it raises an error for documents that have
```json
"@context": "https://spdx.github.io/spdx-3-model/context.json",
```
It doesn't appear to think that this remote context is correctly formatted. I did a little quick [research][1] on this error and it appears that the context itself might not be quite correctly formatted, needing a `@context` of it's own?

[1]: https://stackoverflow.com/questions/61033069/rdflib-invalid-remote-context-when-testing-on-local-sever

**Comment by maxhbr** [comment]
I think this should be two issues:
1. an issue here in the spec parser, that the generation seems to have problems
2. an issue in spdx-3-model which explains the current issues with JSON-LD and that it can not be used right now. And that might be solved without fixing the parser here.

I am not sure if the move of the issue was good, as it now hides the problems in the spdx-3-model repo.

**Comment by zvr** [comment]
Ah, sorry @maxhbr . I had no idea that the issue "might be solved without fixing the parser". How would that work?

**Comment by maxhbr** [comment]
We could manually edit the context file to fix it. 

(Working on the spec-parser is currently not possible as there are some non-public refactoring or rewrite changes outstanding.)

**Comment by zvr** [comment]
@maxhbr Agree -- I am of the opinion that issues should be present where they can be fixed.

If you think there is a way to solve it in the model repo, please open a new issue there.

**Comment by maxhbr** [comment]
This Issue should be fixed, was closed via https://github.com/spdx/spec-parser/pull/75
